markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num
gems: [jekyll-paginate]

blog:
    name: Wang`s Blog                                                # 博客名称
    description:                                         # 博客描述
    title: 我的博客                                               # 网页标题
    url: unibss.com                                                # 博客地址
    duoshuo:                                             # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name: wangwm                                               # 作者名称
    email: 294117190@qq.com                                              # 邮箱地址
    weibo: http://weibo.com/mancowang                                              # 微博地址
    github: mambablack.github.io                                             # GitHub地址
    logo: /res/img/logo/baymax.jpg                                               # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
